/*
	Creates the tables required for Collaborate Ultra integration.
    Currently targeted at MySql - will need data-type modifications to run against Oracle
			nvarchar -> nvarchar2
            varchar -> varchar2
            numeric -> number
*/

CREATE TABLE IF NOT EXISTS VC_ULTRA_SESSIONS(
	SESSION_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    SESSION_NAME NVARCHAR(255),
    START_TIME DATETIME,
    END_TIME DATETIME,
    BOUNDARY_TIME INTEGER,
    CREATOR_ID NVARCHAR(32),
    ALLOW_GUEST CHAR(5),
    GUEST_URL VARCHAR(500),
    NO_END_DATE CHAR(5),
    SHOW_PROFILE CHAR(5),
    PARTICIPANT_CAN_USE_TOOLS CHAR(5),
    CAN_SHARE_VIDEO CHAR(5),
    CAN_SHARE_AUDIO CHAR(5),
    CAN_POST_MESSAGE CHAR(5),
    CAN_ANNOTATE_WHITEBOARD CHAR(5),
    MUST_BE_SUPERVISED CHAR(5),
    OPEN_CHAIR CHAR(5),
    RAISE_HAND_ON_ENTER CHAR(5),
    ALLOW_IN_SESSION_INVITES CHAR(5),
    CAN_DOWNLOAD_RECORDING CHAR(5),
    OCCURRENCE_TYPE CHAR(1),
    CREATED_DATE DATETIME,
    MODIFIED_DATE DATETIME,
    GUEST_ROLE VARCHAR(255),
    EDITING_PERMISSION VARCHAR(255),
    ACCESS_TYPE NUMERIC(20,0)
);

CREATE TABLE IF NOT EXISTS VC_ULTRA_SESSION_ENROLS(
	ENROLMENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    EDITING_PERMISSION VARCHAR(255),
    LAUNCHING_ROLE VARCHAR(255),
    USER_ID VARCHAR(255),
    SESSION_ID VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS VC_ULTRA_USERS(
	USER_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    FIRST_NAME NVARCHAR(255),
    LAST_NAME NVARCHAR(255),
    USER_NAME NVARCHAR(255),
    DISPLAY_NAME NVARCHAR(255),
    EMAIL NVARCHAR(255),
    USER_ROLE VARCHAR(255),
    AVATAR_URL VARCHAR(255),
    IS_INTERNAL CHAR(5),
    USER_UID VARCHAR(255),
    CREATED_DATE DATETIME,
    MODIFIED_DATE DATETIME
);

CREATE TABLE IF NOT EXISTS VC_ULTRA_RECORDINGS(
	RECORDING_ID NUMERIC(20,0) NOT NULL PRIMARY KEY,
    SESSION_START_TIME DATE,
    CAN_DOWNLOAD VARCHAR(5),
    DURATION VARCHAR(255),
    SESSION_NAME VARCHAR(255),
    CREATED_DATE DATE,
    OWNER_ID VARCHAR(255),
    NAME VARCHAR(255),
    RESTRICTED VARCHAR(5),
    MEDIA_NAME VARCHAR(255),
    EDITING_PERMISSION VARCHAR(255),
    MODIFIED_DATE DATE
);

CREATE TABLE IF NOT EXISTS VC_ULTRA_CONTEXTS(
	CONTEXT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    CONTEXT_LABEL VARCHAR(255),
    CONTEXT_NAME VARCHAR(255),
    CONTEXT_TITLE VARCHAR(255),
    CONTEXT_EXTID VARCHAR(255)
);